export let items: Item[] = [
  { id: 1, name: "Espresso", desc: "Strong coffee shot", price: 4.5, img: "https://picsum.photos/seed/coffee1/200/200" },
  { id: 2, name: "Iced Latte", desc: "Smooth milk coffee", price: 5.0, img: "https://picsum.photos/seed/coffee2/200/200" },
  { id: 3, name: "Cappuccino", desc: "Coffee with milk foam", price: 5.5, img: "https://picsum.photos/seed/coffee3/200/200" },
  { id: 4, name: "Mushroom Coffee", desc: "Coffee with medicinal mushrooms", price: 6.0, img: "https://picsum.photos/seed/coffee4/200/200" },
  { id: 5, name: "Egg Coffee", desc: "Vietnamese style egg coffee", price: 5.5, img: "https://picsum.photos/seed/coffee5/200/200" },
  { id: 6, name: "Banana Cold Brew Latte", desc: "Banana flavored cold brew", price: 6.5, img: "https://picsum.photos/seed/coffee6/200/200" },
  { id: 7, name: "Americano", desc: "Espresso with hot water", price: 4.0, img: "https://picsum.photos/seed/coffee7/200/200" },
  { id: 8, name: "Mocha", desc: "Chocolate flavored coffee", price: 5.5, img: "https://picsum.photos/seed/coffee8/200/200" },
  { id: 9, name: "Flat White", desc: "Smooth milk coffee with espresso", price: 5.0, img: "https://picsum.photos/seed/coffee9/200/200" },
  { id: 10, name: "Macchiato", desc: "Espresso with milk foam", price: 4.5, img: "https://picsum.photos/seed/coffee10/200/200" },
  { id: 11, name: "Iced Frappe", desc: "Chilled milk coffee", price: 5.0, img: "https://picsum.photos/seed/coffee11/200/200" },
  { id: 12, name: "Iced Mocha", desc: "Chilled chocolate coffee", price: 5.5, img: "https://picsum.photos/seed/coffee12/200/200" },
  { id: 13, name: "Caramel Latte", desc: "Coffee with caramel syrup", price: 6.0, img: "https://picsum.photos/seed/coffee13/200/200" },
  { id: 14, name: "Hazelnut Latte", desc: "Coffee with hazelnut flavor", price: 6.0, img: "https://picsum.photos/seed/coffee14/200/200" },
  { id: 15, name: "Irish Coffee", desc: "Coffee with whiskey and cream", price: 7.0, img: "https://picsum.photos/seed/coffee15/200/200" },
  { id: 16, name: "Ristretto", desc: "Short and strong espresso", price: 4.5, img: "https://picsum.photos/seed/coffee16/200/200" },
  { id: 17, name: "Café au Lait", desc: "Coffee with steamed milk", price: 5.0, img: "https://picsum.photos/seed/coffee17/200/200" },
  { id: 18, name: "Cinnamon Latte", desc: "Coffee with cinnamon spice", price: 6.0, img: "https://picsum.photos/seed/coffee18/200/200" },
  { id: 19, name: "Turmeric Latte", desc: "Golden milk latte with coffee", price: 6.5, img: "https://picsum.photos/seed/coffee19/200/200" },
  { id: 20, name: "Vanilla Latte", desc: "Coffee with vanilla flavor", price: 6.0, img: "https://picsum.photos/seed/coffee20/200/200" },
  { id: 20, name: "Matcha Latte", desc: "Iced Matcha tea", price: 6.0, img: "https://picsum.photos/seed/coffee20/200/200" },
  { id: 19, name: "Vietnamese Coffee", desc: "Vietnamese style Coffee", price: 6.5, img: "https://picsum.photos/seed/coffee19/200/200" },
  { id: 20, name: "Tiramisu Latte", desc: "Coffee with Tiramisu flavored foam", price: 6.0, img: "https://picsum.photos/seed/coffee20/200/200" },
  { id: 20, name: "Lavender Latte", desc: "Coffee mixed with lavender flavored herb", price: 6.0, img: "https://picsum.photos/seed/coffee20/200/200" },
  { id: 20, name: "Ube Latte", desc: "Coffee mixed with Ube flavor", price: 6.0, img: "https://picsum.photos/seed/coffee20/200/200" },
  { id: 20, name: "Cafe cubano", desc: "An espresso shot which is sweetened", price: 6.0, img: "https://picsum.photos/seed/coffee20/200/200" },
  { id: 20, name: "Breve", desc: "Coffee with a latte base & half-and-half", price: 6.0, img: "https://picsum.photos/seed/coffee20/200/200" },

  
];